# Generated by Django 5.0.4 on 2024-04-17 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_lesson_course'),
        ('users', '0002_user_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='сумма оплаты')),
                ('date', models.DateField(auto_now=True, verbose_name='дата оплаты')),
                ('payment_method', models.CharField(choices=[('card', 'Карта'), ('cash', 'Наличные'), ('transfer', 'Перевод')], max_length=100, verbose_name='Способ оплаты')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.course', verbose_name='Оплаченный курс')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
