# Generated by Django 5.0.4 on 2024-04-17 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_lesson_course'),
        ('users', '0003_pays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pays',
            name='amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='сумма оплаты'),
        ),
        migrations.AlterField(
            model_name='pays',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.course', verbose_name='Оплаченный курс'),
        ),
        migrations.AlterField(
            model_name='pays',
            name='date',
            field=models.DateField(auto_now=True, null=True, verbose_name='дата оплаты'),
        ),
        migrations.AlterField(
            model_name='pays',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('card', 'Карта'), ('cash', 'Наличные'), ('transfer', 'Перевод')], max_length=100, null=True, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='pays',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
