# Generated by Django 5.0.4 on 2024-05-01 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_pays_amount_alter_pays_course_alter_pays_date_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pays",
            options={"verbose_name": "Оплата", "verbose_name_plural": "Оплаты"},
        ),
        migrations.AddField(
            model_name="pays",
            name="link",
            field=models.URLField(
                blank=True, max_length=400, null=True, verbose_name="Ссылка на оплату"
            ),
        ),
        migrations.AddField(
            model_name="pays",
            name="session_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="ID сессии"
            ),
        ),
        migrations.AlterField(
            model_name="pays",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
