# Generated by Django 5.0.4 on 2024-04-30 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0003_course_owner_lesson_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="url",
            field=models.URLField(blank=True, null=True, verbose_name="ссылка"),
        ),
        migrations.AddField(
            model_name="lesson",
            name="url",
            field=models.URLField(blank=True, null=True, verbose_name="ссылка"),
        ),
    ]
