# Generated by Django 5.0.4 on 2024-05-06 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0006_subscription_is_sub"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="course_subscription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscription",
                to="materials.course",
                verbose_name="курс в подписке",
            ),
        ),
    ]
